# -*- coding: utf-8 -*-
"""PrakAlgo7realtime

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sL56HxtJ_1IoKfChA5TpujxLY8OKjbi-
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')

def hitung_faktorial(n):
    if n < 0:
        return "Faktorial tidak dapat dihitung untuk bilangan negatif."
    elif n == 0 or n == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, n + 1):
            hasil *= i
        return hasil

bilangan = int(input("nilai: "))

print(f"Faktorial dari {bilangan} adalah {hitung_faktorial(bilangan)}")

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')

def hitung_vokal_dan_konsonan(kalimat):
    jumlah_vokal = 0
    jumlah_konsonan = 0

    kalimat = kalimat.lower()

    for karakter in kalimat:
        if karakter.isalpha():
            if karakter in 'aeiou':
                jumlah_vokal += 1
            else:
                jumlah_konsonan += 1

    return jumlah_vokal, jumlah_konsonan

kalimat_input = input("Masukkan sebuah kalimat: ")

vokal, konsonan = hitung_vokal_dan_konsonan(kalimat_input)
print(f"Jumlah huruf vokal: {vokal}")
print(f"Jumlah huruf konsonan: {konsonan}")

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')
def pangkat_kubik(angka):
    return angka ** 3

def cek_pembagian_tiga(angka):
    if angka % 3 == 0:
        return pangkat_kubik(angka)
    else:
        return "False"

angka = int(input("Masukkan nilai: "))

hasil = cek_pembagian_tiga(angka)

if hasil != "False":
    print(f"Hasilnya adalah {hasil}")
else:
    print(hasil)